export HF_HUB_OFFLINE=1
export TRANSFORMERS_OFFLINE=1
TF_CPP_MIN_LOG_LEVEL=0 VLLM_USE_XLA_GPU=1 CUDA_VISIBLE_DEVICES=3 PJRT_DEVICE=CUDA GPU_NUM_DEVICES=1 VLLM_USE_V1=1 VLLM_LOGGING_LEVEL=DEBUG vllm serve Qwen/Qwen2.5-3B-Instruct
